// actionTypes.ts
export enum TodoActionTypes {
  ADD_TODO = "ADD_TODO",
  TOGGLE_TODO = "TOGGLE_TODO",
  REMOVE_TODO = "REMOVE_TODO",
  MARK_COMPLETED = "MARK_COMPLETED",
  MARK_INCOMPLETE = "MARK_INCOMPLETE",
  FILTER_TODOS = "FILTER_TODOS",
  MARK_ALL_COMPLETED = "MARK_ALL_COMPLETED",
  UPDATE_SEARCH_TERM = "UPDATE_SEARCH_TERM",
}

export enum ExtraActionTypes {
  TOGGLE_THEME = "TOGGLE_THEME",
  SET_LANGUAGE = "SET_LANGUAGE",
}
